In [ ]:
import time

In [ ]:
import sklearn

In [ ]:
import pandas as pd
import numpy as np
import json
from sklearn.impute import SimpleImputer
from sklearn.metrics import root_mean_squared_error as rmse, f1_score as f1, accuracy_score as acc, precision_score as pr, recall_score as rc, mean_squared_error as mse
import math

In [ ]:
import warnings

def fxn():
    warnings.warn("deprecated", DeprecationWarning)

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    fxn()

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
# df_mis = pd.read_json('https://raw.githubusercontent.com/KSTSV/diploma/refs/heads/main/data01.json')
# df_tar = pd.read_json('https://raw.githubusercontent.com/KSTSV/diploma/refs/heads/main/data01_tar.json')

In [ ]:
# dfm1 = pd.DataFrame(df_mis.loc[2].to_dict())
# dft1 = pd.DataFrame(df_tar.loc[2].to_dict())


# dfm1 = dfm1[sorted(dfm1.columns)]
# dft1 = dft1[sorted(dfm1.columns)]

In [ ]:
for i in range(1, 6):
  file_mis = '/content/drive/MyDrive/Диплом/Датасеты/данные диплом/0'+str(i)+'/data0'+str(i) +'.json'
  file_tar = '/content/drive/MyDrive/Диплом/Датасеты/данные диплом/0'+str(i)+'/data0'+str(i) +'_tar.json'

In [ ]:
data_mis = pd.read_json(file_mis)
data_tar =  pd.read_json(file_tar)

dfm1 = pd.DataFrame(data_mis.loc[1].to_dict())
dft1 = pd.DataFrame(data_tar.loc[1].to_dict())

dfm1 = dfm1[sorted(dfm1.columns)].reset_index(drop = True)
dft1 = dft1[sorted(dfm1.columns)].reset_index(drop = True)

In [ ]:
cat_cols = ['gndr', 'marital_stat', 'initiative1_employer',
       'initiative2_persona', 'money_what_employer', 'money_what_persona',
       'money_what_free_other', 'is_spec_crs', 'profwrk']

ord_cols = ['edu', 'change_sal',
       'title_wrk', 'incm']

cat_ord = ['gndr', 'marital_stat', 'initiative1_employer',
       'initiative2_persona', 'money_what_employer', 'money_what_persona',
       'money_what_free_other', 'is_spec_crs', 'profwrk', 'edu', 'change_sal',
       'title_wrk', 'incm']

int_ord = ['agea', 'agewrk', 'fctr_succ1', 'fctr_succ2', 'fctr_succ3',
       'fctr_succ4', 'impmot1', 'impmot2', 'impmot3', 'impmot4', 'impmot5',
       'impmot6', 'impmot7', 'impmot8', 'impmot9', 'mot1', 'mot10', 'mot11',
       'mot12', 'mot13', 'mot14', 'mot2', 'mot3', 'mot4', 'mot5', 'mot6',
       'mot7', 'mot8', 'mot9', 'num_crs', 'plcwrk', 'sal', 'sat_wrk', 'edu', 'change_sal',
       'title_wrk', 'incm']

int_cols = dfm1.drop(cat_cols, axis=1).drop(ord_cols, axis=1).columns


miss_vars= ["marital_stat", "num_crs",
            "mot1", "mot2", "mot3", "mot4", "mot5", "mot6", "mot7", "mot8", "mot9", "mot10", "mot11", "mot12", "mot13", "mot14",
            "edu", "agewrk", "plcwrk", "profwrk", "change_sal", "title_wrk", "sal", "sat_wrk",
            "fctr_succ1", "fctr_succ2", "fctr_succ3", "fctr_succ4",
            "impmot1", "impmot2", "impmot3", "impmot4", "impmot5", "impmot6", "impmot7", "impmot8", "impmot9",
            "agea", "incm"]


mcar = ["marital_stat", "num_crs",
        "mot2", "mot6", "mot9", "mot10", "mot11", "mot12", "mot13",
        "agewrk", "plcwrk", "sat_wrk",
        "fctr_succ3", "fctr_succ4",
        "impmot1", "impmot4", "impmot5", "impmot8", "agea", "incm", "title_wrk"]

mar = ["mot1", "mot3", "mot4", "mot5", "mot7", "mot8", "mot14",
       "edu", "profwrk", "change_sal", "sal", "fctr_succ1",
       "fctr_succ2", "impmot2", "impmot3", "impmot6", "impmot7", "impmot9"]


mcar_cat = ['marital_stat']
mcar_ord = ['incm', 'title_wrk']
mcar_int = ['mot2', 'agea', 'mot9', 'fctr_succ4',
            'mot6', 'mot10', 'mot11', 'mot12', 'mot13',
            'impmot1', 'incm', 'impmot4', 'impmot8', 'fctr_succ3', 'agewrk',
            'plcwrk', 'sat_wrk', 'impmot5', 'num_crs']



mar_int = ['impmot2', 'impmot7', 'mot1', 'mot14', 'impmot6', 'mot7', 'mot3', 'fctr_succ2', 'impmot3', 'mot8', 'mot4', 'impmot9', 'mot5', 'sal', 'fctr_succ1']
mar_cat = ['profwrk']
mar_ord = ['edu', 'change_sal']


not_mis = ['gndr', 'initiative1_employer', 'initiative2_persona', 'is_spec_crs',
       'money_what_employer', 'money_what_free_other', 'money_what_persona']


mis_cat = ['change_sal', 'edu', 'incm', 'marital_stat', 'profwrk', 'title_wrk']


dfm = pd.concat([dfm1[cat_ord], dft1[int_cols]], axis=1) # категориальные переменные
# dfm = pd.concat([dfm1[int_cols], dft1[cat_ord]], axis=1) # инт переменные

dfm = dfm[sorted(dft1.columns)]
dfm

,agea,agewrk,change_sal,edu,fctr_succ1,fctr_succ2,fctr_succ3,fctr_succ4,gndr,impmot1,...,mot6,mot7,mot8,mot9,num_crs,plcwrk,profwrk,sal,sat_wrk,title_wrk
0,27.0,5.0,2.0,NaN,2.0,3.0,2.0,2.0,1,4.0,...,2.0,4.0,4.0,2.0,2.0,2.0,2.0,147857.0,3.0,NaN
1,44.0,23.0,NaN,8.0,6.0,6.0,6.0,6.0,2,6.0,...,6.0,7.0,7.0,6.0,7.0,6.0,NaN,702273.0,6.0,NaN
2,30.0,9.0,2.0,NaN,3.0,3.0,3.0,3.0,1,4.0,...,3.0,4.0,5.0,3.0,3.0,2.0,2.0,237124.0,4.0,NaN
3,37.0,15.0,NaN,7.0,4.0,4.0,4.0,4.0,1,5.0,...,4.0,6.0,6.0,5.0,5.0,4.0,NaN,460455.0,5.0,NaN
4,28.0,6.0,2.0,NaN,2.0,3.0,2.0,2.0,1,4.0,...,2.0,4.0,4.0,3.0,2.0,2.0,2.0,176388.0,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,34.0,13.0,2.0,7.0,3.0,4.0,3.0,3.0,1,5.0,...,3.0,5.0,6.0,4.0,4.0,3.0,NaN,367349.0,5.0,1.0
251,37.0,15.0,NaN,NaN,4.0,4.0,4.0,4.0,1,5.0,...,4.0,6.0,6.0,5.0,5.0,4.0,NaN,458208.0,5.0,1.0
252,29.0,7.0,NaN,NaN,2.0,3.0,2.0,2.0,1,4.0,...,2.0,4.0,5.0,3.0,3.0,2.0,NaN,203843.0,4.0,1.0
253,37.0,16.0,3.0,NaN,4.0,5.0,4.0,4.0,1,5.0,...,4.0,6.0,6.0,5.0,5.0,4.0,3.0,471012.0,5.0,1.0
254,36.0,14.0,2.0,7.0,4.0,4.0,4.0,4.0,1,5.0,...,4.0,6.0,6.0,4.0,4.0,4.0,NaN,429345.0,5.0,1.0

In [ ]:
cols = ['%', 'agea', 'agewrk', 'change_sal', 'edu', 'fctr_succ1', 'fctr_succ2',
       'fctr_succ3', 'fctr_succ4', 'gndr', 'impmot1', 'impmot2', 'impmot3',
       'impmot4', 'impmot5', 'impmot6', 'impmot7', 'impmot8', 'impmot9',
       'incm', 'initiative1_employer', 'initiative2_persona', 'is_spec_crs',
       'marital_stat', 'money_what_employer', 'money_what_free_other',
       'money_what_persona', 'mot1', 'mot10', 'mot11', 'mot12', 'mot13',
       'mot14', 'mot2', 'mot3', 'mot4', 'mot5', 'mot6', 'mot7', 'mot8', 'mot9',
       'num_crs', 'plcwrk', 'profwrk', 'sal', 'sat_wrk', 'title_wrk']


# df = pd.DataFrame(columns = cols)
df = pd.DataFrame()




cols1 = ['%', 'total_rmse', 'total_acc_ord', 'total_f1_ord', 'total_pr_ord', 'total_rc_ord', 'total_acc_cat',
        'total_f1_cat', 'total_pr_cat', 'total_rc_cat']


# df_total = pd.DataFrame(columns = cols1)
df_total = pd.DataFrame()

In [ ]:
pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.11/dist-packages (2.18.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (5.29.4)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (4.13.2)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.71.0)
Requirement already satisfied: tensorboard<2.19,>=2.18 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.18.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.8.0)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.13.0)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.4.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.37.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.0.9)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.15.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.4.26)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow) (3.8)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.19,>=2.18->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [ ]:
import tensorflow as tf
import matplotlib.pyplot as plt

In [ ]:
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import f1_score as f1, accuracy_score as acc

In [ ]:
sc = StandardScaler()
sc.fit(dfm1[int_cols])
dfm1[int_cols] = sc.transform(dfm1[int_cols])

sc.fit(dft1[int_cols])
dft1[int_cols] = sc.transform(dft1[int_cols])

sc.fit(dfm[int_cols])
dfm[int_cols] = sc.transform(dfm[int_cols])

# для категориальных

In [ ]:
# ann = tf.keras.models.Sequential()
# ann.add(tf.keras.layers.Dense(units=6,activation="relu"))
# ann.add(tf.keras.layers.Dense(units=18,activation="relu"))
# ann.add(tf.keras.layers.Dense(units=5,activation="softmax"))

# ann.compile(optimizer="adam",loss="categorical_crossentropy",metrics=['f1_score'])

In [ ]:
cat_ord

['gndr',
 'marital_stat',
 'initiative1_employer',
 'initiative2_persona',
 'money_what_employer',
 'money_what_persona',
 'money_what_free_other',
 'is_spec_crs',
 'profwrk',
 'edu',
 'change_sal',
 'title_wrk',
 'incm']

In [ ]:
df = pd.DataFrame()
df_vars = pd.DataFrame()
from tensorflow.keras.regularizers import l1

In [ ]:
df_time = pd.DataFrame()

df = pd.DataFrame()
df_vars = pd.DataFrame()

df_t = pd.DataFrame()
df_vars_t = pd.DataFrame()
for j in range(5, 6):
  print('Доля пропусков', j)
  print('--------------------------------------')
  file_mis = '/content/drive/MyDrive/датасеты/данные диплом/0'+str(j)+'/data0'+str(j) +'.json'
  file_tar = '/content/drive/MyDrive/датасеты/данные диплом/0'+str(j)+'/data0'+str(j) +'_tar.json'

  data_mis = pd.read_json(file_mis)
  data_tar =  pd.read_json(file_tar)

  for ind in range(300, data_mis.shape[0]):
    start_time = time.time()
    df.loc[ind, '%'] =  j/10

    dfm1 = pd.DataFrame(data_mis.loc[ind].to_dict())
    dft1 = pd.DataFrame(data_tar.loc[ind].to_dict())

    dfm1 = dfm1[sorted(dfm1.columns)].reset_index(drop = True)
    dft1 = dft1[sorted(dfm1.columns)].reset_index(drop = True)

    # dfm = pd.concat([dfm1[int_cols], dft1[cat_ord]], axis=1)
    dfm = pd.concat([dfm1[cat_ord], dft1[int_cols]], axis=1)
    dfm = dfm[sorted(dft1.columns)]

    for i in mis_cat: # mis_cat
        # print(i)
        # print(True)
        y = dft1[i]
        y = pd.get_dummies(y, dummy_na=False, drop_first=False, dtype=int)
        X = dft1.drop(i, axis=1)
        X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=42)


        ann = tf.keras.models.Sequential()
        ann.add(tf.keras.layers.Dense(units=len(y.columns),activation="relu"))
        # ann.add(tf.keras.layers.Dropout(0.5))
        ann.add(tf.keras.layers.Dense(units=6,activation="relu"))
        ann.add(tf.keras.layers.Dense(units=18,activation="relu"))
        ann.add(tf.keras.layers.Dense(units=len(y.columns),activation="softmax"))

        ann.compile(optimizer="adam",loss="categorical_crossentropy",metrics=['f1_score', 'accuracy'])


        ann.fit(X_train, y_train, batch_size=32,epochs = 20, verbose = 0)

        # test_loss = ann.evaluate(x = X_test, y = y_test)
        l = ann.predict(X_test)
        class_pred = np.argmax(l, axis=1)+1

        pred = class_pred[dfm.loc[X_test.index][i].isna() == 1]

        true = dft1.loc[X_test.index][i][dfm.loc[X_test.index][i].isna() == 1]

        t_pred = ann.predict(dft1[dfm[i].isna() == 1].drop(i, axis=1))
        class_pred_t = np.argmax(t_pred, axis=1)+1

        not_imputed = dft1.loc[dft1[dfm[i].isna() != 1].index][i]
        not_imputed = not_imputed.to_list()
        not_imputed.extend(class_pred_t.tolist())

        f1_score = f1(true, pred, average = 'macro')
        ac_score = acc(true, pred)
        # print(ind)
        # print(f1_score, ac_score)

        df.loc[ind, i+'_f1'] = f1_score
        df.loc[ind, i+'_acc'] = ac_score
        df_vars.loc[ind, i] = np.array(not_imputed).var()
        print(df.shape)

    print("--- %s seconds ---" % (time.time() - start_time))
    df_time.loc[ind, 'time'] = time.time() - start_time

    df_t = pd.concat([df_t, df])
    df_t = df_t.drop_duplicates()
    df_vars_t = pd.concat([df_vars_t, df_vars])
    df_vars_t = df_vars_t.drop_duplicates()

    print(df_t.shape)
    print('Обработан датасет №', ind)

    # break

In [ ]:
from google.colab import files

In [ ]:
# pip install pandas

In [ ]:
# import pandas as pd

In [ ]:
# df.to_csv('ann_stat_part5_часть1.csv')
# # df_total.to_excel('ann_sta2_total1_часть1.xlsx')
# df_vars.to_csv('ann_sta5_var4_часть1.csv')


# files.download('ann_stat_part5_часть1.csv')
# # files.download('ann_sta2_total1_часть1.xlsx')
# files.download('ann_sta2_var5_часть1.csv')

# для интервальных

In [ ]:
data_mis = pd.read_json(file_mis)
data_tar =  pd.read_json(file_tar)

dfm1 = pd.DataFrame(data_mis.loc[1].to_dict())
dft1 = pd.DataFrame(data_tar.loc[1].to_dict())

dfm1 = dfm1[sorted(dfm1.columns)].reset_index(drop = True)
dft1 = dft1[sorted(dfm1.columns)].reset_index(drop = True)

In [ ]:
cat_cols = ['gndr', 'marital_stat', 'initiative1_employer',
       'initiative2_persona', 'money_what_employer', 'money_what_persona',
       'money_what_free_other', 'is_spec_crs', 'profwrk']

ord_cols = ['edu', 'change_sal',
       'title_wrk', 'incm']

cat_ord = ['gndr', 'marital_stat', 'initiative1_employer',
       'initiative2_persona', 'money_what_employer', 'money_what_persona',
       'money_what_free_other', 'is_spec_crs', 'profwrk', 'edu', 'change_sal',
       'title_wrk', 'incm']

int_ord = ['agea', 'agewrk', 'fctr_succ1', 'fctr_succ2', 'fctr_succ3',
       'fctr_succ4', 'impmot1', 'impmot2', 'impmot3', 'impmot4', 'impmot5',
       'impmot6', 'impmot7', 'impmot8', 'impmot9', 'mot1', 'mot10', 'mot11',
       'mot12', 'mot13', 'mot14', 'mot2', 'mot3', 'mot4', 'mot5', 'mot6',
       'mot7', 'mot8', 'mot9', 'num_crs', 'plcwrk', 'sal', 'sat_wrk', 'edu', 'change_sal',
       'title_wrk', 'incm']

int_cols = dfm1.drop(cat_cols, axis=1).drop(ord_cols, axis=1).columns


miss_vars= ["marital_stat", "num_crs",
            "mot1", "mot2", "mot3", "mot4", "mot5", "mot6", "mot7", "mot8", "mot9", "mot10", "mot11", "mot12", "mot13", "mot14",
            "edu", "agewrk", "plcwrk", "profwrk", "change_sal", "title_wrk", "sal", "sat_wrk",
            "fctr_succ1", "fctr_succ2", "fctr_succ3", "fctr_succ4",
            "impmot1", "impmot2", "impmot3", "impmot4", "impmot5", "impmot6", "impmot7", "impmot8", "impmot9",
            "agea", "incm"]


mcar = ["marital_stat", "num_crs",
        "mot2", "mot6", "mot9", "mot10", "mot11", "mot12", "mot13",
        "agewrk", "plcwrk", "sat_wrk",
        "fctr_succ3", "fctr_succ4",
        "impmot1", "impmot4", "impmot5", "impmot8", "agea", "incm", "title_wrk"]

mar = ["mot1", "mot3", "mot4", "mot5", "mot7", "mot8", "mot14",
       "edu", "profwrk", "change_sal", "sal", "fctr_succ1",
       "fctr_succ2", "impmot2", "impmot3", "impmot6", "impmot7", "impmot9"]


mcar_cat = ['marital_stat']
mcar_ord = ['incm', 'title_wrk']
mcar_int = ['mot2', 'agea', 'mot9', 'fctr_succ4',
            'mot6', 'mot10', 'mot11', 'mot12', 'mot13',
            'impmot1', 'incm', 'impmot4', 'impmot8', 'fctr_succ3', 'agewrk',
            'plcwrk', 'sat_wrk', 'impmot5', 'num_crs']



mar_int = ['impmot2', 'impmot7', 'mot1', 'mot14', 'impmot6', 'mot7', 'mot3', 'fctr_succ2', 'impmot3', 'mot8', 'mot4', 'impmot9', 'mot5', 'sal', 'fctr_succ1']
mar_cat = ['profwrk']
mar_ord = ['edu', 'change_sal']


not_mis = ['gndr', 'initiative1_employer', 'initiative2_persona', 'is_spec_crs',
       'money_what_employer', 'money_what_free_other', 'money_what_persona']


mis_cat = ['change_sal', 'edu', 'incm', 'marital_stat', 'profwrk', 'title_wrk']


# dfm = pd.concat([dfm1[cat_ord], dft1[int_cols]], axis=1) # категориальные переменные
dfm = pd.concat([dfm1[int_cols], dft1[cat_ord]], axis=1) # инт переменные

dfm = dfm[sorted(dft1.columns)]
dfm

,agea,agewrk,change_sal,edu,fctr_succ1,fctr_succ2,fctr_succ3,fctr_succ4,gndr,impmot1,...,mot6,mot7,mot8,mot9,num_crs,plcwrk,profwrk,sal,sat_wrk,title_wrk
0,27.0,NaN,2.0,6.0,NaN,NaN,NaN,NaN,1,NaN,...,2.0,4.0,4.0,NaN,NaN,NaN,2.0,147857.0,3.0,1.0
1,44.0,NaN,3.0,8.0,NaN,6.0,6.0,6.0,2,NaN,...,NaN,NaN,NaN,6.0,7.0,6.0,3.0,NaN,6.0,1.0
2,NaN,9.0,2.0,6.0,3.0,NaN,3.0,3.0,1,NaN,...,3.0,NaN,5.0,NaN,3.0,NaN,2.0,NaN,4.0,1.0
3,NaN,15.0,3.0,7.0,NaN,NaN,4.0,NaN,1,NaN,...,4.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN,5.0,1.0
4,28.0,NaN,2.0,6.0,NaN,NaN,2.0,NaN,1,NaN,...,2.0,4.0,4.0,NaN,NaN,NaN,2.0,NaN,4.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,34.0,13.0,2.0,7.0,3.0,NaN,NaN,3.0,1,5.0,...,3.0,NaN,NaN,4.0,4.0,3.0,6.0,NaN,NaN,1.0
251,NaN,NaN,3.0,7.0,NaN,4.0,4.0,4.0,1,NaN,...,NaN,6.0,NaN,5.0,5.0,NaN,3.0,NaN,5.0,1.0
252,NaN,NaN,2.0,6.0,2.0,3.0,2.0,2.0,1,4.0,...,NaN,NaN,5.0,NaN,NaN,NaN,2.0,NaN,4.0,1.0
253,NaN,NaN,3.0,7.0,4.0,NaN,4.0,NaN,1,5.0,...,NaN,6.0,6.0,NaN,NaN,4.0,3.0,NaN,NaN,1.0
254,NaN,NaN,2.0,7.0,NaN,4.0,NaN,NaN,1,5.0,...,4.0,6.0,NaN,4.0,NaN,NaN,3.0,NaN,5.0,1.0

In [ ]:
mis_int = ['agea',
 'agewrk',
 'fctr_succ1',
 'fctr_succ2',
 'fctr_succ3',
 'fctr_succ4',
 'impmot1',
 'impmot2',
 'impmot3',
 'impmot4',
 'impmot5',
 'impmot6',
 'impmot7',
 'impmot8',
 'impmot9',
 'mot1',
 'mot10',
 'mot11',
 'mot12',
 'mot13',
 'mot14',
 'mot2',
 'mot3',
 'mot4',
 'mot5',
 'mot6',
 'mot7',
 'mot8',
 'mot9',
 'num_crs',
 'plcwrk',
 'sal',
 'sat_wrk']

In [ ]:
sc = StandardScaler()
sc.fit(dfm1[int_cols])
dfm1[int_cols] = sc.transform(dfm1[int_cols])

sc.fit(dft1[int_cols])
dft1[int_cols] = sc.transform(dft1[int_cols])

sc.fit(dfm[int_cols])
dfm[int_cols] = sc.transform(dfm[int_cols])

In [ ]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))
ann.add(tf.keras.layers.Dense(units=18,activation="relu"))
ann.add(tf.keras.layers.Dense(units=5,activation="sigmoid"))

ann.compile(optimizer="adam",loss="mse",metrics=['rmse'])

In [ ]:
df = pd.DataFrame()
df_vars = pd.DataFrame()
from tensorflow.keras.regularizers import l1
import keras

In [ ]:
from tensorflow.keras.regularizers import l2

In [ ]:
df = pd.DataFrame()
df_time = pd.DataFrame()
df_vars = pd.DataFrame()

df_t = pd.DataFrame()
df_vars_t = pd.DataFrame()
for j in range(5, 6):
  print('Доля пропусков', j)
  print('--------------------------------------')
  file_mis = '/content/drive/MyDrive/Диплом/Датасеты/данные диплом/0'+str(j)+'/data0'+str(j) +'.json'
  file_tar = '/content/drive/MyDrive/Диплом/Датасеты/данные диплом/0'+str(j)+'/data0'+str(j) +'_tar.json'

  data_mis = pd.read_json(file_mis)
  data_tar =  pd.read_json(file_tar)

  for ind in range(38, data_mis.shape[0]):
    start_time = time.time()
    df.loc[ind, '%'] =  j/10

    dfm1 = pd.DataFrame(data_mis.loc[ind].to_dict())
    dft1 = pd.DataFrame(data_tar.loc[ind].to_dict())

    dfm1 = dfm1[sorted(dfm1.columns)].reset_index(drop = True)
    dft1 = dft1[sorted(dfm1.columns)].reset_index(drop = True)

    dfm = pd.concat([dfm1[int_cols], dft1[cat_ord]], axis=1)
    # dfm = pd.concat([dfm1[cat_ord], dft1[int_cols]], axis=1)
    dfm = dfm[sorted(dft1.columns)]

    for i in mis_int: # mis_cat
        # print(i)
        # print(True)
        y = dft1[i]
        # y = pd.get_dummies(y, dummy_na=False, drop_first=False, dtype=int)
        X = dft1.drop(i, axis=1)
        X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=42)


        ann = tf.keras.models.Sequential()
        ann.add(tf.keras.layers.Dense(units=1,activation="relu"))
        ann.add(tf.keras.layers.Dropout(0.5))
        ann.add(tf.keras.layers.Dense(units=6,activation="relu"))
        ann.add(tf.keras.layers.Dense(units=18,activation="relu"))
        ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

        ann.compile(optimizer="adam",loss="mse",metrics=["mse"])#[keras.metrics.RootMeanSquaredError()]


        ann.fit(X_train, y_train, batch_size=32,epochs = 20, verbose = 0) # , verbose = 0

        # test_loss = ann.evaluate(x = X_test, y = y_test)
        l = ann.predict(X_test)
        # class_pred = np.argmax(l, axis=1)+1

        pred = l[dfm.loc[X_test.index][i].isna() == 1]

        true = dft1.loc[X_test.index][i][dfm.loc[X_test.index][i].isna() == 1]

        t_pred = ann.predict(dft1[dfm[i].isna() == 1].drop(i, axis=1))
        # class_pred_t = np.argmax(t_pred, axis=1)+1

        not_imputed = dft1.loc[dft1[dfm[i].isna() != 1].index][i]
        not_imputed = not_imputed.to_list()
        # not_imputed.extend(class_pred_t.tolist())

        # f1_score = f1(true, pred, average = 'macro')
        # ac_score = acc(true, pred)
        rmse_score = rmse(true, pred)
        # print(ind)
        # print(f1_score, ac_score)

        df.loc[ind, i+'_rmse'] = rmse_score
        # df.loc[ind, i+'_acc'] = ac_score
        df_vars.loc[ind, i] = np.array(not_imputed).var()
        print(df.shape)

    print("--- %s seconds ---" % (time.time() - start_time))

    df_t = pd.concat([df_t, df])
    df_t = df_t.drop_duplicates()
    df_vars_t = pd.concat([df_vars_t, df_vars])
    df_vars_t = df_vars_t.drop_duplicates()

    print(df_t.shape)
    print('Обработан датасет №', ind)

    # break

Доля пропусков 5
--------------------------------------
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
(1, 2)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
(1, 3)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
(1, 4)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
(1, 5)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
(1, 6)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(1, 7)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(1, 8)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
(1, 9)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
(1, 10)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
(1, 11)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
(1, 12)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
(1, 13)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(1, 14)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
(1, 15)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(1, 16)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(1, 17)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
(1, 18)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
(1, 19)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
(1, 20)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
(1, 21)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
(1, 22)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(1, 23)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(1, 24)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
(1, 25)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(1, 26)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
(1, 27)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
(1, 28)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
(1, 29)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(1, 30)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
(1, 31)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
(1, 32)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(1, 33)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
(1, 34)
--- 127.25985622406006 seconds ---
(1, 34)
Обработан датасет № 38
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
(2, 34)
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
(2, 34)

KeyboardInterrupt:

In [ ]:
from google.colab import files

In [ ]:
df.to_csv('INT5.csv')
# df_total.to_excel('ann_sta2_total1_часть1.xlsx')
df_vars.to_csv('VAR_INT5.csv')


files.download('INT5.csv')
# files.download('ann_sta2_total1_часть1.xlsx')
files.download('VAR_INT5.csv')